use utility functions in scripts

diff --git a/sh/.config/sh/scripts/magnet b/sh/.config/sh/scripts/magnet
--- a/sh/.config/sh/scripts/magnet
+++ b/sh/.config/sh/scripts/magnet
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
 
-cd ~/Downloads/torrents/.watch || error "Could not find .watch directory."
-[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || error "Bad magnet link."
+error() {
+    source "$HOME/.config/sh/utils/error"
+}
+
+cd ~/Downloads/torrents/.watch || error "could not find .watch directory"
+[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || error "bad magnet link"
 
 hashh=${BASH_REMATCH[1]}
 if [[ "$1" =~ dn=([^&/]+) ]]
